version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Guclusifre*1234
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"

  api:
    build: ./backend
    container_name: todo_api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=Guclusifre*1234
      - DB_NAME=tododb
    depends_on:
      - db

  web:
    build: ./frontend
    container_name: todo_web
    ports:
      - "80:80"
    depends_on:
      - api